
kind: Deployment 
apiVersion: apps/v1
metadata:
  name: nodedep
spec:
  replicas: 1
  selector:
    matchExpressions:
      - {key: env, operator: In, values: [test]}
  template:
    metadata:
      name: nodepod
      labels:
        env: test
    spec:
      containers:
        - name: nodecont
          image: nginx
          ports:
            - containerPort: 80
---    
kind: Service 
apiVersion: v1 
metadata:
  name: nodesvc
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    env: test
  type: NodePort
