kind: Deployment 
apiVersion: apps/v1
metadata:
  name: ngdeploy
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: env, operator: In, values: [test]}
  template:
    metadata:
      name: myngx
      labels:
        env: test
    spec:
      containers:
        - name: c01
          image: nginx
          ports:
            - containerPort: 80
    
    
