kind: Deployment 
apiVersion: apps/v1
metadata:
  name: nodedeploy
spec:
  replicas: 1
  selector:
    matchExpressions:
      - {key: env, operator: In, values: [test]}
  template:
    metadata:
      name: nodepo
      labels:
        env: test
    spec:
      containers:
        - name: c01
          image: nginx
          ports:
            - containerPort: 80
    
    
